services:
  - type: web
    name: text-similarity-api
    env: python
    runtime: python39
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: HF_API_TOKEN
        value: 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
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /health
